language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_deploy:
- |
  if ! [ "$BEFORE_DEPLOY_RUN" ]; then
    export BEFORE_DEPLOY_RUN=1;
    npm run-script build-demo
  fi
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: true
    local-dir: demo/dist
    on:
      tags: true
      branch: master
      repo: DEGJS/numericycle
  - provider: npm
    email: heaper@gmail.com
    api_key:
      secure: 0x1bMYXzlHcugh8DRKDzfk+IpDgAdnBmMmkkrqNXYPvtwtX27I/ik4rI9L5LacJg+t4/hJXYgB8cX4izqie6+PyNOThm07+CvxEga+nbf1h7NMJvOWCzVW5ZSW1bZQWFLas50z6RzPXsMpRqyCH7WIWK7RjLvp3T1YMqT/1cxe8iewWv87q14YpT4QN7aIWqxxKhHMXV96rUqvf6fX5JqPVZy3r9LDaSWhiCWEFThCV8Nflv4KhudB6sJ/zMXYThLAa9hBWDPM8sUEuTJNdJSXC7e68dVf2oTF/UqXjFF+aTyAqxSiMawy2Agm0mTdYjWfWIEMjWjvXQxkQcQgywg3a0ljq7CIy4+doTaVz7DGhDo+RmIV1rxWv4uDWi861hyviRYe6PmS5ojHF5gnW5HtxeZjzftuFVvJRTr4YJJgYX6O5ER77ndqZDjjOv3dC9KoJvCDCpGDbwZjEHTM4vmYOy8mdtonKxbwqB768MTJEsazXFZ7kZaROmcyqvz0ZRF0So/Dm/S0fkrsZ3pPPY1ZXiqP82BhIaKrSIJTzlTZsRAqBjPKFQHzqaHFLNguwkNFYVoF4hihoBpe5O0fpjfhUZe/7CHkrGxKneJzysByUTWQtD4lt/GKQ6omIzZzZBUR6oHHSThLv5b3nY9RcqHUs0XqgcOLOTXDpmKw16qvA=
    on:
      tags: true
      branch: master
      repo: DEGJS/numericycle
